global:
  imagePullSecrets:
    - name: jfrog-edges
replicaCount: 1
mode: client
tunnel:
  client:
    backoff:
      initialIntervalMillis: 1000
      maxIntervalMillis: 12000
      multiplier: 2
    bridges:
      jfrogml:
        concurrency: 4
        type: jfrogml
        local:
          anonymousEndpoints:
            - .*/system/(ping|readiness|liveness)
            - .*/v1/cert/root
            - .*/v1/registry/join
            - .*/v1/config/shared
        remote:
          url: https://bridge.qwak.ai
image:
  registry: repo21edgesawseuw1.jfrog.io/enterprise-docker
  tag: 1.23.1  
  # registry: repo21edgesawseuw1.jfrog.io/enterprise-docker/jfrogml/171292542837.dkr.ecr.us-east-1.amazonaws.com
  # repository: infra/jfbridge
  # tag: feature-JA-17941-22
router:
  serviceRegistry:
    insecure: true
extraSystemYaml:
  bridge:
    jfConnectClient:
      centralAccessTokenService: "generic"
    logging:
      request:
        verbose: true
        tokenIdLoggingEnabled: true
      application:
        level: debug